#!/bin/bash --

# =============================================================================
# Copyright 2017 National Technology & Engineering Solutions of Sandia, LLC
# (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
# Government retains certain rights in this software.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# =============================================================================
# Maintained by Sandia National Laboratories <Netmeld@sandia.gov>
# =============================================================================

###############################################################################
# Dumb wrapper for running ansible-playbook with defaults.
###############################################################################

# Usage information
PROGRAM_NAME=`basename "$0"`;
read -r -d '' USAGE <<EOF
Copies Ansible playbook data to current directory to begin leveraging Ansible
for data fetching.

Usage: $PROGRAM_NAME

Options:
  -h [ --help ]     Show this help message, then exit.
  -v [ --version ]  Show version information, then exit.
EOF

# Version information
read -r -d '' VERSION <<EOF
${PROGRAM_NAME} (Netmeld)
EOF


parse_args_and_configure() {
  local optSpec="hv-:";
  while getopts "$optSpec" opt; do
    case "$opt" in
      -)
        case "${OPTARG}" in
          help)
            echo "${USAGE}";
            exit 0;
          ;;
          version)
            echo "${VERSION}";
            exit 0;
          ;;
          *)
            if [[ "$OPTERR" = 1 ]] && [[ "${optSpec:0:1}" != ":" ]]; then
              (>&2 echo "${PROGRAM_NAME}: illegal option -- ${OPTARG}");
              echo "${USAGE}";
              exit 1;
            fi;
          ;;
        esac;;
      \?|h)
        echo "${USAGE}";
        exit 0;
      ;;
      v)
        echo "${VERSION}";
        exit 0;
      ;;
      *)
        if [[ "$OPTERR" != 1 ]] || [[ "${optSpec:0:1}" = ":" ]]; then
          (>&2 echo "${PROGRAM_NAME}: illegal option -- ${OPTARG}");
          echo "${USAGE}";
          exit 1;
        fi;
      ;;
    esac;
  done;
}


# Main, script entry point
{
  # Globals
  nm_dir="/usr/local/etc/netmeld";
  nma_dir="ansible-playbooks";
  tgt_dir="$(pwd)";

  # Do work
  parse_args_and_configure "$@";

  read -p "Copy ${nm_dir}/${nma_dir} to ${tgt_dir}? [y/n]" -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    if [ ! -d "${tgt_dir}/${nma_dir}" ]; then
      cp -nr "${nm_dir}/${nma_dir}" "${tgt_dir}/.";
      echo 'Files copied, edit defaults and use `ansible-playbook` to run.'
    else
      echo "Aborting, ${nma_dir} already exists at ${tgt_dir}"
      exit 1;
    fi
  else
    echo "Operation aborted";
  fi

  exit 0;
}
