# concat- string concat
# json- jsonb blob
# filter- regex search on strings (if regex matches, we


v2:
  # Required fields
  assessmentStartTime: ".Timestamp"
  _timeFormat: "%Y-%m-%dT%H:%M:%SZ"
  provider: 'aws'
  accountId: ".Account Number"
  checkId: ".Control ID"
  serviceName: ".Service"
  severity: ".Severity"
  recommendation: ".Remediation"
  description: ".Control"
  # Non-required fields
  region: ".Region"
  resourceId: ".Resource ID"
  risk: ".Risk"
  status: ".Status"
  # Extras
  extras:
    recommendationUrl: ".Doc link"
    compliance: ".Level"
v3:
  # Required fields
  assessmentStartTime: ".AssessmentStartTime"
  _timeFormat: "%Y-%m-%dT%H:%M:%S"
  provider: ".Provider"
  accountId: ".AccountId"
  checkId: ".CheckID"
  serviceName: ".ServiceName"
  severity: ".Severity"
  recommendation: ".Remediation.Recommendation.Text"
  description: ".Description"
  # Non-required field
  region: ".Region"
  resourceId: ".ResourceId"
  risk: ".Risk"
  status: ".Status"
  # Extras
  extras:
    findingUniqueId: ".FindingUniqueId"
    profile: ".Profile"
    organizationsInfo: ".OrganizationsInfo" # Object
    checkTitle: ".CheckTitle"
    checkTypes: ".CheckType" # Array of strings
    subServiceName: ".SubServiceName"
    statusExtended: ".StatusExtended"
    resourceArn: ".ResourceArn"
    resourceTags: ".ResourceTags" # Object
    resourceType: ".ResourceType"
    resourceDetails: ".ResourceDetails"
    relatedUrl: ".RelatedUrl"
    recommendationUrl: ".Remediation.Recommendation.Url"
    remediationCode: ".Remediation.Code" # Object
    categories: ".Categories" # Array
    notes: ".Notes"
    compliance: ".Compliance" # Object
ocsf:
  # Required fields
  assessmentStartTime: ".event_time"
  _timeFormat: "%Y-%m-%dT%H:%M:%S.%f"
  provider: ".cloud.provider"
  accountId: ".cloud.account.uid"
  checkId: ".metadata.event_code"
  serviceName: ".resources.[0].group.name"
  severity: ".severity" # .severity_id could also map
  recommendation: ".remediation.desc"
  description: ".finding_info.desc"
  # Non-required fields
  region: ".resources.[0].region"
  resourceId: ".resources.[0].name"
  risk: ".risk_details"
  status: ".status_code"
  # Extras
  extras:
    findingUniqueId: ".finding_info.uid"
    organizationsInfo:
      concat:
        - "Account Name: "
        - ".cloud.account.name"
        - ", Account Org: "
        - ".cloud.org.name"
    checkTitle: ".finding_info.title"
    checkTypes: ".finding_info.types" # Array
    statusExtended: ".status_detail"
    #resources: ".resources"
    resourceArn: ".resources.[0].uid"
    resourceTags: ".resources.[0].labels" # Object
    resourceType: ".resources.[0].type"
    resourceDetails: ".resources.[0].data.details"
    relatedUrl: ".unmapped.related_url"
    recommendationUrl:
      filter:
        source: ".remediation.references" # Array- Have to filter by http
        regex: "^http.*"
        join_str: "\n"
    remediationCode:
      filter:
        source: ".remediation.references" # Array- Have to filter by !http
        regex: "^(?!http).*"
        join_str: "\n"
    categories: ".unmapped.categories" # Array
    notes: ".unmapped.notes"
    compliance: ".unmapped.compliance" # Object with Array values
