---
command_value: "{{ item.invocation.module_args.commands[0] | regex_replace(' ', '_')}}"
item_value: "{{ item.stdout[0] }}"

cmd_list:
- show running-config full
- show startup-config
- show version
- show cdp neighbor detail
- show mac address-table
- show inventory
- show interfaces
- show vlan
- show spanning-tree
