FROM debian:testing-slim

ENV DEBIAN_FRONTEND noninteractive

RUN apt update --quiet --quiet --assume-yes --option Dpkg::Use-Pty=0 \
 && apt install --quiet --quiet --assume-yes --option Dpkg::Use-Pty=0 \
      unzip curl
      
RUN groupadd -r netmeld \
 && useradd -r -s /bin/bash -g netmeld netmeld

USER netmeld

WORKDIR /home/netmeld/setup

USER root

RUN curl -k --silent --location \
      `curl -k --silent \
           https://api.github.com/repos/netmeld/netmeld/releases/latest \
         | grep -oP '"browser_download_url": "\K(.*)(?=")'` \
      --output netmeld-debs.zip \
      && unzip -qq netmeld-debs.zip

RUN apt install --quiet --quiet --assume-yes --option Dpkg::Use-Pty=0 \
      --no-install-suggests \
      ./netmeld-*core.deb

WORKDIR /home/netmeld

USER netmeld

CMD ["/bin/bash"]