FROM netmeld-test-base

ENV NETMELD_DB netmeld_test_all

WORKDIR /home/netmeld/setup

RUN apt install --quiet --quiet --assume-yes --option Dpkg::Use-Pty=0 \
      --no-install-recommends --no-install-suggests \
      ./netmeld-*.deb

WORKDIR /home/netmeld

RUN rm -rf ./setup

WORKDIR /home/netmeld/contents/

CMD ["./toolsuite.sh"]
