FROM netmeld-test-base                                                                                            

ENV NETMELD_DB netmeld_test_import

WORKDIR /home/netmeld/setup

RUN apt install --quiet --quiet --assume-yes --option Dpkg::Use-Pty=0 \
      --no-install-recommends --no-install-suggests \
      ./netmeld-*datalake.deb ./netmeld-*datastore*.deb

RUN apt install --quiet --quiet --assume-yes git

WORKDIR /home/netmeld

RUN rm -rf ./setup

WORKDIR /home/netmeld/contents/datalake-datastore

CMD ["./test.py"]
