FROM netmeld-core

WORKDIR /home/netmeld/setup

USER root

RUN apt install --quiet --quiet --assume-yes --option Dpkg::Use-Pty=0 \
      --no-install-suggests \
      ./netmeld-*tool-clw.deb

WORKDIR /home/netmeld

RUN rm -rf ./setup

USER netmeld

CMD ["/bin/bash"]
