---
- name: "Gather data from Cisco type targets"
  ios_command:
    commands: "{{ item.cmd }}"
  register: cmd
  loop: "{{ cmd_list | flatten(1) }}"
  ignore_errors: yes
  become: "{{ item.become | default('no') }}"
