---
command_value: "{{ item.invocation.module_args.commands[0] | regex_replace(' ', '_')}}"
item_value: "{{ item.stdout[0] }}"

cmd_list:
- cmd: show configuration
  tool: nmdb-import-juniper-conf
- cmd: show configuration | display set
  tool: nmdb-import-juniper-set
- cmd: show configuration | display xml
- cmd: show version detail
- cmd: show arp no-resolve
- cmd: show ethernet-switching table detail
- cmd: show ethernet-switching table extensive
- cmd: show chassis hardware
- cmd: show chassis hardware detail
- cmd: show chassis hardware extensive
- cmd: show ldp neighbor detail
- cmd: show ldp neighbor extensive
- cmd: show system uptime
- cmd: show ntp status no-resolve
