# Schema
#
# # Per-run configuration options
# runtime-options:
#   # Ignore unexpected interface state changes; per phase check
#   ignore-iface-state-change: true|false
#
# # Playbook pre-defined scoping
# intra-network|inter-network:
#   # Stage definition; one per scope as primarily controlled in tool logic
#   stage:
#     # Phase definition; multiple per stage
#     - phase:
#       # Command set; multiple per phase
#       - name: # Text to use for identifying the command set
#         # IPv4 related commands
#         ipv4:
#           # Command; multiple per command set
#           - title: # Text to use for identifying the command
#             cmd: # Command to run
#             opts: # Command options; allows variable replacement
#               - opt1 # Example
#               - opt2 {{ipNet}} # Example with variable replacement
#               - "{{ipNet}}" # Example variable replacement if by self
#         # IPv6 related commands; same schema as IPv4
#         ipv6:
#       # Execute manual test prompt
#       - manual-tests: true|false
#       # Phase optional options (same YAML scope as "phase")
#       # Generate responding hosts file
#       generate-responding-hosts: true|false

runtime-options:
  ignore-iface-state-change: false


templates:
  - phase: &manual-testing
    - name: Manual Testing Prompt
      ipv4: &manual-testing-ipv4
      - title: Manual Tests
        cmd: echo ''
        opts:
          - ; echo 'Finish any manual testing that is using
                    {{linkName}} {{srcIpAddr}}.'
          - ; echo 'Close this xterm when manual testing is complete.'
          - ; echo 'When this xterm is closed,
                    {{linkName}} {{srcIpAddr}} will be deconfigured.'
          - ; while [[ 1 == 1 ]]; do sleep 600; done;
      ipv6: *manual-testing-ipv4

# Phase variable replacement options
# - {{ipNetBcast}} -- the broadcast IP of the target network
# - {{ipNet}} -- the IP subnet of the target network
# - {{linkName}} -- the interface the play is currently using
# - {{respondingHostsPath}} -- path to file containing known alive IPs
# - {{roeExcludedPath}} -- path to file containing IPs excluded from scan
# - {{roeNetworksPath}} -- the IP subnet of the target network
intra-network:
  stage:
    - phase:
      - name: Initial Host Discovery
        ipv4:
          - title: network broadcast ping
            cmd: clw ping -4
            opts:
              - -n
              - -I {{linkName}}
              - -L
              - -c 4
              - -b {{ipNetBcast}}
          - title: global broadcast ping
            cmd: clw ping -4
            opts:
              - -n
              - -I {{linkName}}
              - -L
              - -c 4
              - -b 255.255.255.255
        ipv6:
          - title: all-nodes multicast ping
            cmd: clw ping -6
            opts:
              - -n
              - -I {{linkName}}
              - -L
              - -c 4
              - -b ff02::1
          - title: all-routers multicast ping
            cmd: clw ping -6
            opts:
              - -n
              - -I {{linkName}}
              - -L
              - -c 4
              - -b ff02::2
      - name: Host Discovery and IP Protocol Scans
        ipv4:
          - title: nmap IPv4 ARP host discovery
            cmd: clw nmap
            opts:
              - -n
              - -e {{linkName}}
              - -sn
              - -PR
              - -T4
              - --script '(ip-forwarding)'
              - --excludefile {{roeExcludedPath}}
              - "{{ipNet}}"
          - title: nmap IPv4 IP protocol scan
            cmd: clw nmap
            opts:
              - -n
              - -e {{linkName}}
              - -sO
              - -PR
              - -T4
              - --excludefile {{roeExcludedPath}}
              - "{{ipNet}}"
        ipv6:
          - title: nmap IPv6 ARP host discovery
            cmd: clw nmap -6
            opts:
              - -n
              - -e {{linkName}}
              - -sn
              - -PR
              - -T4
              - --script '(ip-forwarding) or (targets-ipv6-* or ipv6-node-info)'
              - --script-args 'newtargets'
              - --excludefile {{roeExcludedPath}}
              - "{{ipNet}}"
          - title: nmap IPv6 IP protocol scan
            cmd: clw nmap -6
            opts:
              - -n
              - -e {{linkName}}
              - -sO
              - -PR
              - -T4
              - --script '(targets-ipv6-* or ipv6-node-info)'
              - --script-args 'newtargets'
              - --excludefile {{roeExcludedPath}}
              - "{{ipNet}}"
    - phase:
      - name: Default DNS Lookup With Nmap
        ipv4:
          - title: nmap IPv4 DNS lookup, default resolver
            cmd: clw nmap
            opts:
              - -R
              - -sL
              - -T4
              - --resolve-all
              - --excludefile {{roeExcludedPath}}
              - "{{ipNet}}"
        ipv6:
          - title: nmap IPv6 DNS lookup, default resolver
            cmd: clw nmap -6
            opts:
              - -R
              - -sL
              - -T4
              - --resolve-all
              - --excludefile {{roeExcludedPath}}
              - "{{ipNet}}"
    - generate-responding-hosts: true
      phase:
      - name: Port Scans (plus basic info gathering)
        ipv4:
          - title: nmap IPv4 TCP port scan
            cmd: clw nmap
            opts:
              - -n
              - -e {{linkName}}
              - -sS
              - -PR
              - -T4
              - -O
              - --script
                '(banner or dns-nsid or ntp-info or rpcinfo
                  or ssh-hostkey or ssh2-enum-algos or ssl-cert
                  or smtp-commands or smb-os-discovery
                  or smbv2-enabled or vnc-info)'
              - -p `nmdb-export-port-list --tcp-all`
              - -iL {{respondingHostsPath}}
              - --excludefile {{roeExcludedPath}}
          - title: nmap IPv4 UDP port scan
            cmd: clw nmap
            opts:
              - -n
              - -e {{linkName}}
              - -sU
              - -PR
              - -T4
              - -O
              - --script
                '(banner or dns-nsid or ntp-info or rpcinfo
                  or ssh-hostkey or ssh2-enum-algos or ssl-cert
                  or smtp-commands or smb-os-discovery
                  or smbv2-enabled or vnc-info)'
              - -p `nmdb-export-port-list --udp`
              - -iL {{respondingHostsPath}}
              - --excludefile {{roeExcludedPath}}
        ipv6:
          - title: nmap IPv6 TCP port scan
            cmd: clw nmap -6
            opts:
              - -n
              - -e {{linkName}}
              - -sS
              - -PR
              - -T4
              - -O
              - --script
                '(banner or dns-nsid or ntp-info or rpcinfo
                  or ssh-hostkey or ssh2-enum-algos or ssl-cert
                  or smtp-commands or smb-os-discovery
                  or smbv2-enabled or vnc-info)'
              - -p `nmdb-export-port-list --tcp-all`
              - -iL {{respondingHostsPath}}
              - --excludefile {{roeExcludedPath}}
          - title: nmap IPv6 UDP port scan
            cmd: clw nmap -6
            opts:
              - -n
              - -e {{linkName}}
              - -sU
              - -PR
              - -T4
              - -O
              - --script
                '(banner or dns-nsid or ntp-info or rpcinfo
                  or ssh-hostkey or ssh2-enum-algos or ssl-cert
                  or smtp-commands or smb-os-discovery
                  or smbv2-enabled or vnc-info)'
              - -p `nmdb-export-port-list --udp`
              - -iL {{respondingHostsPath}}
              - --excludefile {{roeExcludedPath}}
      - name: Service Scans (most scripts enabled)
        ipv4:
          - title: nmap IPv4 service scan
            cmd: clw nmap
            opts:
              - -n
              - -e {{linkName}}
              - -sS
              - -PR
              - -T4
              - -A
              - --script
                '((default or discovery) and not (external or brute or dos))'
              - -p `nmdb-export-port-list --tcp-all`
              - -iL {{respondingHostsPath}}
              - --excludefile {{roeExcludedPath}}
        ipv6:
          - title: nmap IPv6 service scan
            cmd: clw nmap -6
            opts:
              - -n
              - -e {{linkName}}
              - -sS
              - -PR
              - -T4
              - -A
              - --script
                '((default or discovery) and not (external or brute or dos))'
              - -p `nmdb-export-port-list --tcp-all`
              - -iL {{respondingHostsPath}}
              - --excludefile {{roeExcludedPath}}
    - phase:
      - name: Learned DNS Lookup With Nmap
        ipv4:
          - title: nmap IPv4 DNS lookup, via open port 53
            cmd: echo ''
            opts:
              - ; DNS_SERVERS=`psql site
              - "-A -t -c \"select ip_addr from ports_services
                          where port = '999' and port_state = 'open'\""
              - "| tr '\n' ','`"
              - ; clw nmap
              - -R -sL -T4
              - --dns-servers "${DNS_SERVERS}"
              - --resolve-all
              - --excludefile {{roeExcludedPath}}
              - "{{ipNet}}"
        ipv6:
          - title: nmap IPv6 DNS lookup, via open port 53
            cmd: echo ''
            opts:
              - ; DNS_SERVERS=`psql site
              - "-A -t -c \"select ip_addr from ports_services
                          where port = '999' and port_state = 'open'\""
              - "| tr '\n' ','`"
              - ; clw nmap -6
              - -R -sL -T4
              - --dns-servers "${DNS_SERVERS}"
              - --resolve-all
              - --excludefile {{roeExcludedPath}}
              - "{{ipNet}}"
    - phase: *manual-testing

inter-network:
  stage:
    - phase:
      - name: Host Discovery and IP Protocol Scans
        ipv4:
          - title: nmap IPv4 ICMP host discovery
            cmd: clw nmap
            opts:
              - -n
              - -e {{linkName}}
              - -sn
              - -T4
              - -PE
              - -PP # ICMP Timestamp; not valid for IPv6
              - -PM # ICMP Address Mask; not valid for IPv6
              - -iL {{roeNetworksPath}}
              - --excludefile {{roeExcludedPath}}
          - title: nmap IPv4 port discovery
            cmd: clw nmap
            opts:
              - -n
              - -e {{linkName}}
              - -sn
              - -T4
              - "-PS\
                21-25,49,53,65,80,88,111,123,135-139,161-162,179,389,\
                427,443,445,464,543-544,636,749-751,873,902,\
                1645-1646,1812-1813,2049,3260,3268-3269,3283,3306,3389,3868,\
                4174,5353-5355,5432,5900-5919,8000,8080-8089,8443,8888,\
                9000-9010,9443,10000-10010,10443,49152-49169,\
                65530-65535"
              - "-PA\
                21-25,49,53,65,80,88,111,123,135-139,161-162,179,389,\
                427,443,445,464,543-544,636,749-751,873,902,\
                1645-1646,1812-1813,2049,3260,3268-3269,3283,3306,3389,3868,\
                4174,5353-5355,5432,5900-5919,8000,8080-8089,8443,8888,\
                9000-9010,9443,10000-10010,10443,49152-49169,\
                65530-65535"
              - "-PU\
                49,53,65-69,88,111,123,135-139,161-162,389,427,464,\
                500,543-544,546-547,749-751,902,1645-1646,1812-1813,1985,\
                2049,3268-3269,4174,5353-5355,49152-49169,\
                65530-65535"
              - -iL {{roeNetworksPath}}
              - --excludefile {{roeExcludedPath}}
          - title: nmap IPv4 IP protocol scan
            cmd: clw nmap
            opts:
              - -n
              - -e {{linkName}}
              - -sO
              - -T4
              - -iL {{roeNetworksPath}}
              - --excludefile {{roeExcludedPath}}
        ipv6:
          - title: nmap IPv6 ICMP host discovery
            cmd: clw nmap -6
            opts:
              - -n
              - -e {{linkName}}
              - -sn
              - -T4
              - -PE
              - -iL {{roeNetworksPath}}
              - --excludefile {{roeExcludedPath}}
          - title: nmap IPv6 port discovery
            cmd: clw nmap -6
            opts:
              - -n
              - -e {{linkName}}
              - -sn
              - -T4
              - "-PS\
                21-25,49,53,65,80,88,111,123,135-139,161-162,179,389,\
                427,443,445,464,543-544,636,749-751,873,902,\
                1645-1646,1812-1813,2049,3260,3268-3269,3283,3306,3389,3868,\
                4174,5353-5355,5432,5900-5919,8000,8080-8089,8443,8888,\
                9000-9010,9443,10000-10010,10443,49152-49169,\
                65530-65535"
              - "-PA\
                21-25,49,53,65,80,88,111,123,135-139,161-162,179,389,\
                427,443,445,464,543-544,636,749-751,873,902,\
                1645-1646,1812-1813,2049,3260,3268-3269,3283,3306,3389,3868,\
                4174,5353-5355,5432,5900-5919,8000,8080-8089,8443,8888,\
                9000-9010,9443,10000-10010,10443,49152-49169,\
                65530-65535"
              - "-PU\
                49,53,65-69,88,111,123,135-139,161-162,389,427,464,\
                500,543-544,546-547,749-751,902,1645-1646,1812-1813,1985,\
                2049,3268-3269,4174,5353-5355,49152-49169,\
                65530-65535"
              - -iL {{roeNetworksPath}}
              - --excludefile {{roeExcludedPath}}
          - title: nmap IPv6 IP protocol scan
            cmd: clw nmap -6
            opts:
              - -n
              - -e {{linkName}}
              - -sO
              - -T4
              - --script '(targets-ipv6-* or ipv6-node-info)'
              - --script-args 'newtargets'
              - -iL {{roeNetworksPath}}
              - --excludefile {{roeExcludedPath}}
    - generate-responding-hosts: true
      phase:
      - name: DNS Lookup With Nmap
        ipv4:
          - title: nmap IPv4 DNS lookup, default resolver
            cmd: clw nmap
            opts:
              - -R
              - -sL
              - --resolve-all
              - -iL {{respondingHostsPath}}
              - --excludefile {{roeExcludedPath}}
        ipv6:
          - title: nmap IPv6 DNS lookup, default resolver
            cmd: clw nmap -6
            opts:
              - -R
              - -sL
              - --resolve-all
              - -iL {{respondingHostsPath}}
              - --excludefile {{roeExcludedPath}}
    - phase:
      - name: Port Scans (plus basic info gathering)
        ipv4:
          - title: nmap IPv4 TCP port scan
            cmd: clw nmap
            opts:
              - -n
              - -e {{linkName}}
              - -Pn
              - -sS
              - -T4
              - -O
              - --script
                '(banner or dns-nsid or ntp-info or rpcinfo
                  or ssh-hostkey or ssh2-enum-algos or ssl-cert
                  or smtp-commands or smb-os-discovery
                  or smbv2-enabled or vnc-info)'
              - -p `nmdb-export-port-list --tcp-all`
              - -iL {{respondingHostsPath}}
              - --excludefile {{roeExcludedPath}}
          - title: nmap IPv4 UDP port scan
            cmd: clw nmap
            opts:
              - -n
              - -e {{linkName}}
              - -Pn
              - -sU
              - -T4
              - -O
              - --script
                '(banner or dns-nsid or ntp-info or rpcinfo
                  or ssh-hostkey or ssh2-enum-algos or ssl-cert
                  or smtp-commands or smb-os-discovery
                  or smbv2-enabled or vnc-info)'
              - -p `nmdb-export-port-list --udp`
              - -iL {{respondingHostsPath}}
              - --excludefile {{roeExcludedPath}}
        ipv6:
          - title: nmap IPv6 TCP port scan
            cmd: clw nmap -6
            opts:
              - -n
              - -e {{linkName}}
              - -Pn
              - -sS
              - -T4
              - -O
              - --script
                '(banner or dns-nsid or ntp-info or rpcinfo
                  or ssh-hostkey or ssh2-enum-algos or ssl-cert
                  or smtp-commands or smb-os-discovery
                  or smbv2-enabled or vnc-info)'
              - -p `nmdb-export-port-list --tcp-all`
              - -iL {{respondingHostsPath}}
              - --excludefile {{roeExcludedPath}}
          - title: nmap IPv6 UDP port scan
            cmd: clw nmap -6
            opts:
              - -n
              - -e {{linkName}}
              - -Pn
              - -sU
              - -T4
              - -O
              - --script
                '(banner or dns-nsid or ntp-info or rpcinfo
                  or ssh-hostkey or ssh2-enum-algos or ssl-cert
                  or smtp-commands or smb-os-discovery
                  or smbv2-enabled or vnc-info)'
              - -p `nmdb-export-port-list --udp`
              - -iL {{respondingHostsPath}}
              - --excludefile {{roeExcludedPath}}
    - phase:
      - name: Learned DNS Lookup With Nmap
        ipv4:
          - title: nmap IPv4 DNS lookup, via open port 53
            cmd: echo ''
            opts:
              - ; DNS_SERVERS=`psql site
              - "-A -t -c \"select ip_addr from ports_services
                          where port = '999' and port_state = 'open'\""
              - "| tr '\n' ','`"
              - ; clw nmap
              - -R -sL -T4
              - --dns-servers "${DNS_SERVERS}"
              - --resolve-all
              - --excludefile {{roeExcludedPath}}
              - "{{ipNet}}"
        ipv6:
          - title: nmap IPv6 DNS lookup, via open port 53
            cmd: echo ''
            opts:
              - ; DNS_SERVERS=`psql site
              - "-A -t -c \"select ip_addr from ports_services
                          where port = '999' and port_state = 'open'\""
              - "| tr '\n' ','`"
              - ; clw nmap -6
              - -R -sL -T4
              - --dns-servers "${DNS_SERVERS}"
              - --resolve-all
              - --excludefile {{roeExcludedPath}}
              - "{{ipNet}}"
    - phase: *manual-testing
