---
command_value: "{{ item.invocation.module_args.commands[0] | regex_replace(' ', '_')}}"
item_value: "{{ item.stdout[0] }}"

cmd_list:
- cmd: terminal length 0
- cmd: show host name
- cmd: show host os
- cmd: show version all
- cmd: show arp
- cmd: show lldp neighbors detail
- cmd: show system connections
- cmd: show system uptime
- cmd: show ntp
- cmd: show dhcp client leases

pcmd_list:
- cmd: show configuration
  tool: nmdb-import-vyos
- cmd: show dhcp leases
- cmd: show dhcpv6 client leases
- cmd: show dhcpv6 server leases
