---
command_value: "{{ item.invocation.module_args.commands[0] | regex_replace(' ', '_')}}"
item_value: "{{ item.stdout[0] }}"

cmd_list:
- terminal length 0
- show configuration
- show version all
- show arp
- show lldp neighbors detail
- show system connections
- show system uptime
- show ntp
- show dhcp client leases
- show dhcp leases
- show dhcpv6 client leases
- show dhcpv6 server leases
