---
# NOTE: \u2215, math symbol division slash, is different from / to the OS
command_value: "{{ item.cmd | join('_') | regex_replace('/', '\u2215') }}"
item_value: "{{ item.stdout }}"

cmd_list:
- cmd: whoami /all
- cmd: systeminfo
# IP address and route information
- cmd: ipconfig /allcompartments /all
  tool: nmdb-import-ipconfig
- cmd: netstat -nr
- cmd: netstat -ano
- cmd: get-netipconfiguration -all -allcompartments -detailed
- cmd: get-netipinterface -includeallcompartments
- cmd: get-netneighbor -includeallcompartments
- cmd: get-netroute -includeallcompartments
# Get packages and/or services
- cmd: ps
- cmd: get-process
- cmd: get-process -includeusername
