name: PR-CI

on:
  pull_request:
    branches: [ master ]
    types: [ synchronize, ready_for_review ]

jobs:
  BuildTest:
    runs-on: ubuntu-latest
    container: netmeld/netmeld-dev:latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: cmake -S . -B build

    - name: Build Source
      run: cmake --build build -j 2

    - name: Build Tests
      run: cmake --build build -j 2 --target Test.netmeld

    - name: Test
      run: |
        cd build
        ctest
